baseURL = 'https://elecbrandy.github.io/freshpink/'
languageCode = 'en-us'
title = 'freshPink'

[[menus.main]]
name = 'Home'
url = '/freshpink/'
weight = 10

[[menus.main]]
name = 'TAGS'
url = '/freshpink/tags/'
weight = 20

[[menus.main]]
name = 'ABOUT'
url = '/freshpink/about/'
weight = 30

[module]
  [module.hugoVersion]
    extended = true
    min = "0.116.0"

[params]
  githubUsername = "elecbrandy"
  copyright = "Copyright © 2024 elecbrandy"

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
